### ISSUE TITLE
How do I choose the correct ECC curve collection?

### ISSUE THREAD

**Issue by takmune** [Infineon/mtb-example-optiga-mqtt-client#2]
Hi,

I'm trying to connect [CYSBSYSKIT-DEV-01](https://github.com/Infineon/getstarted-optiga-trust-m/tree/main/psoc62_secure_development_kit)(running [mtb-example-optiga-mqtt-client](https://github.com/Infineon/mtb-example-optiga-mqtt-client)) to "Mosquitto MQTT Broker".
It fails in TLS handshake sequence.
I think that the cause is a mismatch between the "Supported Groups" specified in "ClientHello" and the "ECC curve collection" supported by OPTIGA TRUST M.

***[A part of ClientHello message]***
```
            Extension: supported_groups (len=6)`
                Type: supported_groups (10)`
                Length: 6`
                Supported Groups List Length: 4
                Supported Groups (2 groups)
                    Supported Group: secp256r1 (0x0017)
                    Supported Group: x25519 (0x001d)
```
***[A part of ServerKeyExchange message]***
```
TLSv1.2 Record Layer: Handshake Protocol: Server Key Exchange
        Content Type: Handshake (22)
        Version: TLS 1.2 (0x0303)
        Length: 115
        Handshake Protocol: Server Key Exchange
            Handshake Type: Server Key Exchange (12)
            Length: 111
            EC Diffie-Hellman Server Params
                Curve Type: named_curve (0x03)
                Named Curve: x25519 (0x001d)
```

***[ECC curve collection" supported by OPTIGA TRUST M]***
https://github.com/Infineon/optiga-trust-m#features-table
ECC NIST P256/384
ECC NIST P521, ECC Brainpool P256/384/512 r1
(*I use V3)

How do I choose the correct ECC curve collection?

**Comment by ShaikKarishma0** [comment]
Hi @takmune,

Mosquitto is not mentioned as a tested setup for this code example. 
Anyway, you can try to use mbedtls library by uncommenting the following [line](https://github.com/Infineon/mtb-example-optiga-mqtt-client/blob/master/configs/mbedtls_user_config.h#L167) in mbedtls_user_config.h file.

**Comment by takmune** [comment]
Thank you for your advice!

It succeeded in connecting to mosquitto MQTT Broker by changing as follows.

mbedtls_user_config.h(L156-L168)
```
#undef MBEDTLS_ECP_DP_SECP192R1_ENABLED
#undef MBEDTLS_ECP_DP_SECP224R1_ENABLED
//#undef MBEDTLS_ECP_DP_SECP256R1_ENABLED
//#undef MBEDTLS_ECP_DP_SECP384R1_ENABLED
//#undef MBEDTLS_ECP_DP_SECP521R1_ENABLED
#undef MBEDTLS_ECP_DP_SECP192K1_ENABLED
#undef MBEDTLS_ECP_DP_SECP224K1_ENABLED
#undef MBEDTLS_ECP_DP_SECP256K1_ENABLED
//#undef MBEDTLS_ECP_DP_BP256R1_ENABLED
//#undef MBEDTLS_ECP_DP_BP384R1_ENABLED
//#undef MBEDTLS_ECP_DP_BP512R1_ENABLED
#undef MBEDTLS_ECP_DP_CURVE25519_ENABLED
#undef MBEDTLS_ECP_DP_CURVE448_ENABLED
```

The above settings match the following specifications.
```
ECC NIST P256/384
ECC NIST P521, ECC Brainpool P256/384/512 r1
```
