### ISSUE TITLE
MQTT Connection is failing

### ISSUE THREAD

**Issue by krantik** [Infineon/mtb-example-optiga-mqtt-client#3]
We are using this project to connect to AWS and are getting this cryptic error. Any info to help us debug further? We see the certificate from the Optiga printed on the terminal after it says the client is connecting to the MQTT Broker.

MQTT connection failed with error code 0x8060009. Retrying in 2000 ms. Retries left: 149

**Comment by ShaikKarishma0** [comment]
Hi @krantik,

Can you please confirm if you have changed the MQTT_BROKER_ADDRESS and MQTT_SNI_HOSTNAME to your custom endpoint in the configs/mqtt_client_config.h file? (Please follow [readme](https://github.com/Infineon/mtb-example-optiga-mqtt-client#step-2-configure-the-application))
And which version of MTB are you using?

**Comment by krantik** [comment]
@ShaikKarishma0 Thank you for looking into this. We are able to get this sample working you can close this request. We thought since we don't need the CLIENT_PRIVATE_KEY we removed it, didn't notice the comment that it is needed for mbedtls which caused the TLS handshake to fail. Hopefully the response codes can be improved for all the projects, they seem to give cryptic error codes.
